#include "translator.h"

#include <filesystem>
#include <fstream>
#include <algorithm>
#include <istream>
#include <iostream>
#include <string>

namespace fs = std::filesystem;

void CSharpTranslator::translateFiles(
    const std::vector<fs::path> &filepaths,
    const fs::path &outputDir,
    const std::string &projectName)
{
    // Ensure output directory exists
    fs::create_directories(outputDir);

    writeProjectFiles(outputDir, projectName);

    // Translate each file in the list
    for (auto filepath : filepaths)
    {
        std::ifstream f(filepath);
        json ast = json::parse(f);
        fs::path outputFilepath = outputDir / (ast["filename"].get<std::string>() + ".cs");
        translateAST(ast, projectName, outputFilepath);
    }
}

void CSharpTranslator::translateAST(const json &AST, const std::string &projectName, fs::path &outputFilepath)
{
    std::ofstream file(outputFilepath);

    // Get the test category
    std::string testCategory = toPascalCase(outputFilepath.stem().string());
    std::string prefix = "unit_test_";
    if (prefix.find(prefix))
    {
        testCategory.erase(0, prefix.length());
    }

    // Top of file
    file << "// Generated by translator" << "\n";
    file << "namespace " + projectName + ";\n\n";

    // Order the top level items (globals, functions, tests) based on location
    struct TopLevelItem {
        int location;
        std::string kind;
        json payload;
    };

    std::vector<TopLevelItem> items;

    // Function to add each top level item to an array for sorting
    auto addToArray = [&](std::string key, std::string kindName)
    {
        if (!AST.contains(key) || !AST[key].is_array()) return;

        for (auto &jsonItem : AST[key])
        {
            items.push_back(TopLevelItem{jsonItem["location"], kindName, jsonItem});
        }
    };

    // Add all items
    addToArray("globals", "global");
    addToArray("functions", "function");
    addToArray("tests", "test");

    // Sort items
    std::sort(
        items.begin(),
        items.end(),
        [](const TopLevelItem &a, const TopLevelItem &b) {
            return a.location < b.location;
        });

    // Translate in order
    for (auto item : items)
    {
        if (item.kind == "global") translateVarDecl(item.payload, file);
        else if (item.kind == "test") translateTestCase(item.payload, file, testCategory);
        else if (item.kind == "function") translateFunctionDecl(item.payload, file);
    }

    // End of file
}

void CSharpTranslator::translateTestCase(const json &testCase, std::ofstream &file, std::string &category)
{
    // Set category ("unit_test_color" == "Color")
    std::string categoryTrait = "[Trait(\"Category\", \"" + category + "\")]\n";

    // Set tags as xUnit "functions"
    std::string functionTrait = "[Trait(\"Function\", \"";
    int tagCount = testCase["tags"].size();

    for (int i = 0; i < tagCount; ++i)
    {
        if (i > 0)
            functionTrait += ", ";

        functionTrait += testCase["tags"][i];
    }

    functionTrait += "\")]\n";

    // Set test name as the class name 
    std::string className = toPascalCase(testCase["name"]);
    std::string classDecl = "public class " + className + "\n{\n";

    // OPEN TEST
    file << categoryTrait;
    file << functionTrait;
    file << classDecl;

    // TEST BODY
    file << "    // Some body goes here\n";

    // CLOSE TEST
    file << "}\n";
}

void CSharpTranslator::translateVarDecl(const json &varDecl, std::ofstream &file)
{
    file << "// var\n\n";
}

void CSharpTranslator::translateFunctionDecl(const json &funcDecl, std::ofstream &file)
{
    file << "// function\n\n";
}

void CSharpTranslator::writeProjectFiles(const fs::path &outputDir, const std::string &projectName)
{
    fs::path filepath = outputDir / (projectName + ".csproj");

    // Project file
    std::ofstream projFile(filepath);

    projFile << R"(<!-- Generated by translator -->
<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net6.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <IsPackable>false</IsPackable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="coverlet.collector" Version="6.0.2" />
        <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.12.0" />
        <PackageReference Include="xunit" Version="2.9.2" />
        <PackageReference Include="xunit.runner.visualstudio" Version="2.8.2" />
    </ItemGroup>

    <!-- Include C# bindings in project -->
    <ItemGroup>
        <Compile Include="../../../../../generated/csharp/SplashKit.cs" />
    </ItemGroup>

</Project>
)";

    // Global usings file
    std::ofstream usingsFile("generated/csharp/GlobalUsings.cs");

    usingsFile << R"(// Generated by translator
global using Xunit;
global using SplashKitSDK;
global using static SplashKitSDK.SplashKit;)";
}

std::string CSharpTranslator::toPascalCase(const std::string& name)
{
    std::string result;
    bool capitalize = true;

    for (char c : name)
    {
        if (c == '_' || c == ' ')
        {
            capitalize = true;
        }
        else
        {
            result += capitalize ? static_cast<char>(std::toupper(c)) : c;
            capitalize = false;
        }
    }

    return result;
}
