#include "translator.h"

#include <filesystem>
#include <fstream>
#include <algorithm>
#include <istream>
#include <iostream>
#include <memory>
#include <string>

#include "ast.h"

namespace fs = std::filesystem;

void CSharpTranslator::translateASTSet(
    const std::vector<CustomAST> &ASTs,
    const fs::path &outputDir,
    const std::string &projectName)
{
    // Ensure output directory exists
    fs::create_directories(outputDir);

    writeProjectFiles(outputDir, projectName);

    // Translate each AST in the list
    for (auto &AST : ASTs)
    {
        std::string filename = AST.filename + ".cs";
        fs::path outputFilepath = outputDir / filename;
        translateAST(AST, projectName, outputFilepath);
    }
}

void CSharpTranslator::translateAST(
    const CustomAST &AST,
    const std::string &projectName,
    const fs::path &outputFilepath)
{
    std::ofstream file(outputFilepath);

    // Get the test category
    std::string testCategory = toPascalCase(outputFilepath.stem().string());
    std::string prefix = "unit_test_";
    if (prefix.find(prefix))
    {
        testCategory.erase(0, prefix.length());
    }

    // Top of file
    file << "// Generated by translator" << "\n";
    file << "namespace " + projectName + ";\n\n";

    // std::vector<ASTNode> nodes;

    // nodes.insert(nodes.end(), AST.globals.begin(), AST.globals.end());
    // nodes.insert(nodes.end(), AST.functions.begin(), AST.functions.end());
    // nodes.insert(nodes.end(), AST.tests.begin(), AST.tests.end());

    
    // Sort items
    // std::sort(
    //     nodes.begin(),
    //     nodes.end(),
    //     [](const ASTNode &a, const ASTNode &b) {
    //         return a.location < b.location;
    //     });

    for (auto &test : AST.tests)
    {
        writeTestCase(test, file, testCategory, AST.globals, AST.functions);
    }

    
    // Translate in order
    // for (auto &node : AST.topLevelNodes)
    // {
    //     if (auto *global = dynamic_cast<VariableDeclarationStatement*>(node.get()))
    //     {
    //         writeVarDeclStmt(*global, file);
    //     }
    //     else if (auto *testCase = dynamic_cast<TestCase*>(node.get()))
    //     {
    //         writeTestCase(*testCase, file, testCategory);
    //     }
    //     else if (auto *function = dynamic_cast<FunctionDeclaration*>(node.get()))
    //     {
    //         writeFunctionDecl(*function, file);
    //     }
    // }

    // End of file
}

void CSharpTranslator::writeTestCase(
    const TestCase &testCase,
    std::ofstream &file,
    std::string &category,
    const std::vector<VariableDeclarationStatement> &globals,
    const std::vector<FunctionDeclaration> &functions)
{
    // Set category ("unit_test_color" == "Color")
    std::string categoryTrait = "[Trait(\"Category\", \"" + category + "\")]\n";

    // Set tags as xUnit "functions"
    std::string functionTrait = "[Trait(\"Function\", \"";
    int tagCount = testCase.tags.size();

    for (int i = 0; i < tagCount; ++i)
    {
        if (i > 0)
            functionTrait += ", ";

        functionTrait += testCase.tags[i];
    }

    functionTrait += "\")]\n";

    // Set test name as the class name 
    std::string className = toPascalCase(testCase.name);
    std::string classDecl = "public class " + className + "\n{\n";

    // OPEN TEST
    file << categoryTrait;
    file << functionTrait;
    file << classDecl;
    increaseIndent();

    // TEST BODY
    // Global variables
    for (auto &global : globals)
    {
        writeVarDeclStmt(global, file);
    }

    // Top level functions
    for (auto &func : functions)
    {
        writeFunctionDecl(func, file);
    }

    // CLOSE TEST
    decreaseIndent();
    file << "}\n";
}

void CSharpTranslator::writeVarDeclStmt(const VariableDeclarationStatement &varDecl, std::ofstream &file)
{
    std::string csType = translateType(varDecl.variable.type);
    std::string varName = varDecl.variable.name;
    std::string expression = translateExpression(*varDecl.variable.initializer);

    file << indt() << csType + " " + varName << " = ";
    file << expression << ";\n\n";
}

std::string CSharpTranslator::translateExpression(const Expression &expr)
{
    if (auto *binary = dynamic_cast<const BinaryExpression*>(&expr))
    {
        return translateBinaryExpr(*binary);
    }
    else if (auto *reference = dynamic_cast<const ReferenceExpression*>(&expr))
    {
        return translateRefExpr(*reference);
    }
    else if (auto *literal = dynamic_cast<const LiteralExpression*>(&expr))
    {
        return translateLiteralExpr(*literal);
    }

    throw std::runtime_error("Unsupported Expression type in translateExpression");
}

std::string CSharpTranslator::translateBinaryExpr(const BinaryExpression &expr)
{
    std::string result;
    result += translateExpression(*expr.left);
    result += " " + expr.op + " ";
    result += translateExpression(*expr.right);
    return result;
}

std::string CSharpTranslator::translateRefExpr(const ReferenceExpression &expr)
{
    return expr.name;
}

std::string CSharpTranslator::translateCallExpr(const CallExpression &expr)
{
    std::string result = expr.functionName;
    result += "(";
    int argCount = expr.arguments.size();

    // Add arguments
    for (int i = 0; i < argCount; ++i)
    {
        if (i > 0)
            result += ", ";

        result += translateExpression(*expr.arguments[i]);
    }

    result += ")";
    return result;
}

std::string CSharpTranslator::translateLiteralExpr(const LiteralExpression &expr)
{
    return expr.value;
}

void CSharpTranslator::writeFunctionDecl(const FunctionDeclaration &funcDecl, std::ofstream &file)
{
    file << indt() << funcDecl.returnType << " " << funcDecl.name << "(";

    int paramCount = funcDecl.parameters.size();

    // Add arguments
    for (int i = 0; i < paramCount; ++i)
    {
        if (i > 0)
            file << ", ";

        file << translateParameter(funcDecl.parameters[i]);
    }

    file << ")\n";
    file << indt() << "{\n";

    increaseIndent();
    file << indt();
    file << "// Body goes here\n";
    decreaseIndent();
    file << indt() << "}\n\n";
}

std::string CSharpTranslator::translateParameter(const Parameter &parameter)
{
    std::string result = translateType(parameter.type) + " " + parameter.name;
    if (parameter.defaultValue)
    {
        result += " = " + translateExpression(*parameter.defaultValue);
    }
    return result;
}

void CSharpTranslator::writeProjectFiles(const fs::path &outputDir, const std::string &projectName)
{
    fs::path filepath = outputDir / (projectName + ".csproj");

    // Project file
    std::ofstream projFile(filepath);

    projFile << R"(<!-- Generated by translator -->
<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net6.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <IsPackable>false</IsPackable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="coverlet.collector" Version="6.0.2" />
        <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.12.0" />
        <PackageReference Include="xunit" Version="2.9.2" />
        <PackageReference Include="xunit.runner.visualstudio" Version="2.8.2" />
    </ItemGroup>

    <!-- Include C# bindings in project -->
    <ItemGroup>
        <Compile Include="../../../../../generated/csharp/SplashKit.cs" />
    </ItemGroup>

</Project>
)";

    // Global usings file
    std::ofstream usingsFile("generated/csharp/GlobalUsings.cs");

    usingsFile << R"(// Generated by translator
global using Xunit;
global using SplashKitSDK;
global using static SplashKitSDK.SplashKit;)";
}

std::string CSharpTranslator::toPascalCase(const std::string& name)
{
    std::string result;
    bool capitalize = true;

    for (char c : name)
    {
        if (c == '_' || c == ' ')
        {
            capitalize = true;
        }
        else
        {
            result += capitalize ? static_cast<char>(std::toupper(c)) : c;
            capitalize = false;
        }
    }

    return result;
}

std::string CSharpTranslator::translateType(const std::string &cppType)
{
    auto it = typeMap.find(cppType);
    if (it != typeMap.end()) return it->second; 
    return cppType;
}

// Type map
const std::unordered_map<std::string, std::string> CSharpTranslator::typeMap = {
    {"int", "int"},
    {"float", "float"},
    {"double", "double"},
    {"_Bool", "bool"},
    {"char", "char"},
    {"std::string", "string"}
};
