#include "translator.h"

#include <cctype>
#include <filesystem>
#include <fstream>
#include <memory>
#include <string>

#include "ast.h"

namespace fs = std::filesystem;

void CSharpTranslator::translateASTSet(
    const std::vector<CustomAST> &ASTs,
    const fs::path &outputDir,
    const std::string &projectName)
{
    // Ensure output directory exists
    fs::create_directories(outputDir);

    writeProjectFiles(outputDir, projectName);

    // Translate each AST in the list
    for (auto &AST : ASTs)
    {
        std::string filename = AST.filename + ".cs";
        fs::path outputFilepath = outputDir / filename;
        writeAST(AST, projectName, outputFilepath);
    }
}

void CSharpTranslator::writeAST(
    const CustomAST &AST,
    const std::string &projectName,
    const fs::path &outputFilepath)
{
    std::ofstream file(outputFilepath);

    // Get category
    std::string category = AST.filename;
    std::string prefix = "unit_test_";
    if (category.find(prefix) == 0)
    {
        category.erase(0, prefix.length());
    }
    category = toPascalCase(category);

    // Top of file
    file << "// Generated by translator" << "\n";
    file << "namespace " + projectName + ";\n\n";

    // Declare  class
    file << "public class UnitTest" + category + "\n{\n";
    increaseIndent();

    // Globals
    if (!AST.globals.empty() && !AST.functions.empty())
        writeGlobals(AST, file);

    for (auto &test : AST.tests)
    {
        writeTestCase(test, file, category);
    }

    // Clear globals for the next file
    globals.clear();
    // End of file
    decreaseIndent();
    file << "}\n";
    file.close();
}

void CSharpTranslator::writeGlobals(const CustomAST &AST, std::ofstream &file)
{
    // Declare GeneratedGlobals class
    file << indt() << "private static class " + globalClassName + "\n" + indt() + "{\n";
    increaseIndent();

    // Global variables
    for (const auto &global : AST.globals)
    {
        writeVarDeclStmt(global, file);
        // Add to list of globals for refence when calling
        globals.insert(global.variable.name);
    }

    // Top level functions
    for (const auto &func : AST.functions)
    {
        writeFunctionDecl(func, file);
        // Add to list of globals for refence when calling
        globals.insert(func.name);
    }

    decreaseIndent();
    file << indt() << "}\n\n";
}

void CSharpTranslator::writeTestCase(
    const TestCase &testCase,
    std::ofstream &file,
    std::string category)
{
    // Set category ("unit_test_color" == "Color")
    std::string categoryTrait = "[Trait(\"Category\", \"" + category + "\")]\n";

    // Set tags as xUnit "functions"
    std::string functionTrait = "[Trait(\"Function\", \"";
    int tagCount = testCase.tags.size();

    for (int i = 0; i < tagCount; ++i)
    {
        if (i > 0)
            functionTrait += ", ";

        functionTrait += testCase.tags[i];
    }

    functionTrait += "\")]\n";

    // Set test name as the class name 
    std::string className = toPascalCase(testCase.name);
    std::string classDecl = "public class " + className + "\n";

    // OPEN TEST
    file << indt() << categoryTrait;
    file << indt() << functionTrait;
    file << indt() << classDecl;
    file << indt() << "{\n";
    increaseIndent();

    // Body
    for (auto &section : testCase.sections)
    {
        writeSection(section, file);
    }

    // CLOSE TEST
    decreaseIndent();
    file << indt() << "}\n\n";
}

void CSharpTranslator::writeBody(const std::vector<std::shared_ptr<Statement>> &body, std::ofstream &file)
{
    // Body
    for (const auto &statement : body)
    {
        writeStatement(*statement, file);
    }
}

void CSharpTranslator::writeStatement(const Statement &statement, std::ofstream &file)
{
    if (auto *assertion = dynamic_cast<const AssertionStatement*>(&statement))
    {
        writeAssertion(*assertion, file);
    }
    else if (auto *varDeclStmt = dynamic_cast<const VariableDeclarationStatement*>(&statement))
    {
        writeVarDeclStmt(*varDeclStmt, file);
    }
    else if (auto *exprStmt = dynamic_cast<const ExpressionStatement*>(&statement))
    {
        writeExprStmt(*exprStmt, file);
    }
}

void CSharpTranslator::writeSection(const Section &section, std::ofstream &file)
{
    // Set display name
    file << indt() << "[Fact(DisplayName = \"" + section.name + "\")]\n";
    // Set class name
    file << indt() << "public void " + toPascalCase(section.name) + "()\n";
    file << indt() << "{\n";

    // Section body
    increaseIndent();

    writeBody(section.body, file);

    // End section
    decreaseIndent();
    file << indt() << "}\n\n";
}

void CSharpTranslator::writeAssertion(const AssertionStatement &assertion, std::ofstream &file)
{
    // Get the expression
    if (auto *expr = dynamic_cast<const Expression*>(assertion.expression.get()))
    {
        // Get the type
        if (auto *bin = dynamic_cast<const BinaryExpression*>(expr))
        {
            // Binary expression
            if (bin->op == "==")
            {
                std::string left;
                std::string right;

                // If there's a literal or unary on the right, swap places
                if (dynamic_cast<const LiteralExpression*>((bin->right).get()) ||
                    dynamic_cast<const UnaryExpression*>((bin->right).get()))
                {
                    right = translateExpression(*(bin->left));
                    left = translateExpression(*(bin->right));
                }
                else
                {
                    left = translateExpression(*(bin->left));
                    right = translateExpression(*(bin->right));
                }

                // Select correct assertion type based on expression
                std::string assertion;

                if (left == "null")
                {
                    assertion = "Null(" + right + ")";
                }
                else if (left == "true")
                {
                    assertion = "True(" + right + ")";
                }
                else if (left == "false")
                {
                    assertion = "False(" + right + ")";
                }
                else
                    assertion = "Equal(" + left + ", " + right + ")";

                file << indt() << "Assert." << assertion + ";\n";
            }
        }
    }
}

void CSharpTranslator::writeVarDeclStmt(const VariableDeclarationStatement &varDecl, std::ofstream &file)
{
    std::string csType = translateType(varDecl.variable.type);
    std::string varName = toCamelCase(varDecl.variable.name);

    std::string declaration = varDecl.isGlobal ? "public static " : ""; 
    declaration += csType + " " + varName;

    file << indt() << declaration;

    // If it's initialised
    if (varDecl.variable.initializer)
    {
        file << " = " << translateExpression(*varDecl.variable.initializer);
    }
    file << ";\n\n";
}

void CSharpTranslator::writeExprStmt(const ExpressionStatement &exprStmt, std::ofstream &file)
{
    std::string expr = translateExpression(*exprStmt.expression);

    // If it's a call to the logger, skip it
    if (expr.find("EnableLogging") != std::string::npos ||
        expr.find("DisableLogging") != std::string::npos)
        return;

    file << indt() << expr + ";\n";
}

void CSharpTranslator::writeReturnStmt(const ReturnStatement &returnStmt, std::ofstream &file)
{
    file << indt() << "return " << translateExpression(*returnStmt.value) + ";\n";
}

std::string CSharpTranslator::translateExpression(const Expression &expr)
{
    if (auto *binary = dynamic_cast<const BinaryExpression*>(&expr))
    {
        return translateBinaryExpr(*binary);
    }
    else if (auto *unary = dynamic_cast<const UnaryExpression*>(&expr))
    {
        return translateUnaryExpr(*unary);
    }
    else if (auto *reference = dynamic_cast<const ReferenceExpression*>(&expr))
    {
        return translateRefExpr(*reference);
    }
    else if (auto *literal = dynamic_cast<const LiteralExpression*>(&expr))
    {
        return translateLiteralExpr(*literal);
    }
    else if (auto *call = dynamic_cast<const CallExpression*>(&expr))
    {
        return translateCallExpr(*call);
    }

    throw std::runtime_error("Unsupported Expression type in Translator: translateExpression()" + std::string(typeid(expr).name()));
}

std::string CSharpTranslator::translateBinaryExpr(const BinaryExpression &expr)
{
    std::string result;
    result += translateExpression(*expr.left);
    result += " " + expr.op + " ";
    result += translateExpression(*expr.right);
    return result;
}

std::string CSharpTranslator::translateUnaryExpr(const UnaryExpression &expr)
{
    return expr.op + translateExpression(*expr.operand);
}

std::string CSharpTranslator::translateRefExpr(const ReferenceExpression &expr)
{
    std::string result;

    // Check if it's a global variable
    if (globals.find(expr.name) != globals.end())
    {
        result += globalClassName + ".";
    }
    result += toCamelCase(expr.name);

    return result;
}

std::string CSharpTranslator::translateCallExpr(const CallExpression &expr)
{
    std::string result;
    // Check if it's a global function
    if (globals.find(expr.functionName) != globals.end())
    {
        result += globalClassName + ".";
    }

    result += toPascalCase(expr.functionName) + "(";
    int argCount = expr.arguments.size();

    // Add arguments
    for (int i = 0; i < argCount; ++i)
    {
        if (i > 0)
            result += ", ";

        result += translateExpression(*expr.arguments[i]);
    }

    result += ")";
    return result;
}

std::string CSharpTranslator::translateLiteralExpr(const LiteralExpression &expr)
{
    std::string result = expr.value;
    if (expr.type == "string") result = "\"" + result + "\"";
    else if (expr.type == "nullptr_t") result = "null";
    return result;
}

void CSharpTranslator::writeFunctionDecl(const FunctionDeclaration &funcDecl, std::ofstream &file)
{
    std::string declaration = funcDecl.isGlobal ? "public static " : ""; 
    declaration += funcDecl.returnType + " " + toPascalCase(funcDecl.name);

    file << indt() << declaration << "(";

    int paramCount = funcDecl.parameters.size();

    // Add arguments
    for (int i = 0; i < paramCount; ++i)
    {
        if (i > 0)
            file << ", ";

        file << translateParameter(funcDecl.parameters[i]);
    }

    file << ")\n";
    file << indt() << "{\n";

    increaseIndent();
    file << indt();
    file << "// Body goes here\n";
    decreaseIndent();
    file << indt() << "}\n\n";
}

std::string CSharpTranslator::translateParameter(const Parameter &parameter)
{
    std::string result = translateType(parameter.type) + " " + parameter.name;
    if (parameter.defaultValue)
    {
        result += " = " + translateExpression(*parameter.defaultValue);
    }
    return result;
}

void CSharpTranslator::writeProjectFiles(const fs::path &outputDir, const std::string &projectName)
{
    fs::path filepath = outputDir / (projectName + ".csproj");

    // Project file
    std::ofstream projFile(filepath);

    projFile << R"(<!-- Generated by translator -->
<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net6.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <IsPackable>false</IsPackable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="coverlet.collector" Version="6.0.2" />
        <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.12.0" />
        <PackageReference Include="xunit" Version="2.9.2" />
        <PackageReference Include="xunit.runner.visualstudio" Version="2.8.2" />
    </ItemGroup>

    <!-- Include C# bindings in project -->
    <ItemGroup>
        <Compile Include="../../../../../../generated/csharp/SplashKit.cs" />
    </ItemGroup>

</Project>
)";
    projFile.close();

    // Global usings file
    std::ofstream usingsFile(outputDir / "GlobalUsings.cs");

    usingsFile << R"(// Generated by translator
global using Xunit;
global using SplashKitSDK;
global using static SplashKitSDK.SplashKit;)";

    usingsFile.close();
}

std::string CSharpTranslator::toCamelCase(const std::string& name)
{
    // Convert to PascalCase
    std::string result = toPascalCase(name);

    // Lower case first letter
    if (!result.empty())
    {
        result[0] = static_cast<char>(std::tolower(result[0]));
    }
    return result;
}

std::string CSharpTranslator::toPascalCase(const std::string& name)
{
    // Special cases taken from SplashKit Translator: lib/core_ext/string.rb
    const std::unordered_map<std::string, std::string> specialCases = {
        {"rgb", "RGB"},
        {"hsb", "HSB"},
        {"css", "CSS"},
        {"ip", "IP"},
        {"tcp", "TCP"},
        {"udp", "UDP"},
        {"uri", "URI"},
        {"rgba", "RGBA"}
    };

    // Split into words and capitalise
    std::string s = name;
    std::string result;
    std::string delimiters =
        "abcdefghijklmnopqrstuvwxyz"
        "ABCDEFGHIJKLMNOPQRSTUVWXYZ"
        "0123456789";

    while (true)
    {
        size_t pos = s.find_first_not_of(delimiters);
        std::string word = s.substr(0, pos);

        if (!word.empty())
        {
            // Replace special cases, or capitalise first letter
            auto it = specialCases.find(word);

            if (it != specialCases.end()) 
            {
                word = it->second;
            } 
            else 
            {
                word[0] = static_cast<char>(std::toupper(word[0]));
            }

            result += word;
        }

        if (pos == std::string::npos) break;
        s.erase(0, pos + 1);
    }

    return result;
}

std::string CSharpTranslator::translateType(const std::string &cppType)
{
    // Type map for standard C++ types
    // Mappings from SplashKit Translator: src/translators/csharp.rb
    const std::unordered_map<std::string, std::string> typeMap = {
        {"int", "int"},
        {"float", "float"},
        {"double", "double"},
        {"_Bool", "bool"},
        {"char", "char"},
        {"std::string", "string"},
        {"int8_t", "byte"},
        {"short", "short"},
        {"int64_t", "long"},
        {"byte", "byte"},
        {"unsigned char", "byte"},
        {"unsigned int", "uint"},
        {"unsigned short", "ushort"}
    };

    auto it = typeMap.find(cppType);

    // If it's a known type, convert it, otherwise convert to PascalCase
    if (it != typeMap.end())
        return it->second; 
    else
        return toPascalCase(cppType);
}
